### ISSUE TITLE
Exiting thread

### ISSUE THREAD

**Issue by AlfredoCopp** [narfster/leopard_directshow#1]
Hello, 
what would be the safest way to exit the thread t2 in main.cpp?
From within the code, I mean.

**Comment by narfster** [comment]
what exactly would you like to do?
I could assist if you explain more
t2 is the main capture loop

**Comment by AlfredoCopp** [comment]
I'd like to have an atomic bool variable which i could control with thread1_func (t1),
when a certain key is pressed to set the variable to false. 
T2 should recognize that the atomic bool is false and stop executing.

EDIT: I tried messing with "pEventInterface->WaitForCompletion(INFINITE, &evCode);" inside directshow.cpp, but without success.

**Comment by narfster** [comment]
what camera are you using?
okay, so I added a keystoke called 's'
it will stop the camera run, is that what you needed?
also updated project to VS2019 and removed some compilation errors
